<a href="https://colab.research.google.com/github/ahnafsayem/python_practice/blob/main/Data%20Analysis%20and%20Visualization%20Tools/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#making one dimensional Array

a = np.array([1,2,3,4,5])
print(a)

a[0]

#chceking dimension
print(a.ndim)

#checking shape
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize #print the byte size

8

In [ ]:
a.size

5

In [ ]:
a.shape

(5,)

In [ ]:
#changing data type
a = np.array([1,2,3,4,5], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [ ]:
#making two dimensional array

b = np.array([[1,2,3],[4,5,6]])
print(b)

print(b[1])

b[1]=[6,7,8]
print(b)

#chceking dimension
print(b.ndim)

#checking shape
print(b.shape)

[[1 2 3]
 [4 5 6]]
[4 5 6]
[[1 2 3]
 [6 7 8]]
2
(2, 3)


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
c = np.array([[1,5,3],[4,7,6]])
c.shape

(2, 3)

In [ ]:
c.reshape(3,2)

array([[1, 5],
       [3, 4],
       [7, 6]])

In [ ]:
c.min()

1

In [ ]:
c.max()

7

In [ ]:
c.sum()

26

In [ ]:
c.sum(axis=0)

array([ 5, 12,  9])

In [ ]:
c.sum(axis=1)

array([ 9, 17])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x[1,2] #row0,row1.rpw2 and column0,column1,column2

6

In [ ]:
x[0:2,1]

array([2, 5])

In [ ]:
x[-1]

array([7, 8, 9])

In [ ]:
x[-1,0:2]

array([7, 8])

In [ ]:
#going through all column

x[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
for row in x:
  print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
for row in x:
  for cell in row:
    print(cell)

1
2
3
4
5
6
7
8
9


In [ ]:
#another way

for cell in x.flatten():
  print(cell)

1
2
3
4
5
6
7
8
9


In [ ]:
#nditer


for x in np.nditer(x,order='C'): #C order i;e row wise
  print(x)

1
2
3
4
5
6
7
8
9
