<a href="https://colab.research.google.com/github/ahnafsayem/python_practice/blob/main/Data%20Analysis%20and%20Visualization%20Tools/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#making one dimensional Array

a = np.array([1,2,3,4,5])
print(a)

a[0]

#chceking dimension
print(a.ndim)

#checking shape
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize #print the byte size

8

In [ ]:
a.size

5

In [ ]:
a.shape

(5,)

In [ ]:
#changing data type
a = np.array([1,2,3,4,5], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [ ]:
#making two dimensional array

b = np.array([[1,2,3],[4,5,6]])
print(b)

print(b[1])

b[1]=[6,7,8]
print(b)

#chceking dimension
print(b.ndim)

#checking shape
print(b.shape)

[[1 2 3]
 [4 5 6]]
[4 5 6]
[[1 2 3]
 [6 7 8]]
2
(2, 3)


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])