<a href="https://colab.research.google.com/github/ahnafsayem/python_practice/blob/main/Data%20Analysis%20and%20Visualization%20Tools/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#making one dimensional Array

a = np.array([1,2,3,4,5])
print(a)

a[0]

#chceking dimension
print(a.ndim)

#checking shape
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [ ]:
#making two dimensional array

b = np.array([[1,2,3],[4,5,6]])
print(b)

print(b[1])

b[1]=[6,7,8]
print(b)

#chceking dimension
print(b.ndim)

#checking shape
print(b.shape)

[[1 2 3]
 [4 5 6]]
[4 5 6]
[[1 2 3]
 [6 7 8]]
2
(2, 3)
